branches:
  only:
    - master

language: ruby
cache: bundler
rvm:
  - 2.0.0-p648
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - 2.6.0
  - 2.7.0
  - 3.0.0

before_install:
  # There is a bug in travis. When using system ruby, bundler is not
  # installed and causes the default install action to fail.
  - if [ "$TRAVIS_RUBY_VERSION" = "system" ]; then sudo gem install "bundler:~> 1.17.0"; else gem install "bundler:~> 1.17.0"; fi

matrix:
  include:
    - rvm: 2.5.0
      env: COCOAPODS_CI_TASKS=LINT

script:
  - bundle exec rake spec:all
  - if [ "$COCOAPODS_CI_TASKS" = "LINT" ]; then bundle exec danger; fi

addons:
  code_climate:
    repo_token: fcf708528e1eca6e8a8bf8f7be3bd24e4478b019c4cd7860325c141dd52aa152
