# Sets Travis to run the Ruby specs on OS X machines to be as close as possible
# to the user environment.
#
language: objective-c
addons:
 code_climate:
   repo_token: fcf708528e1eca6e8a8bf8f7be3bd24e4478b019c4cd7860325c141dd52aa152 

env:
  - RVM_RUBY_VERSION=system
  # - RVM_RUBY_VERSION=1.8.7-p358

before_install:
  - curl http://curl.haxx.se/ca/cacert.pem -o /usr/local/share/cacert.pem
  - source ~/.rvm/scripts/rvm
  - if [[ $RVM_RUBY_VERSION != 'system' ]]; then rvm install $RVM_RUBY_VERSION; fi
  - rvm use $RVM_RUBY_VERSION
  - if [[ $RVM_RUBY_VERSION == 'system' ]]; then sudo gem install bundler --no-ri --no-rdoc; else gem install bundler --no-ri --no-rdoc; fi

install:
  - bundle install --without=documentation --path ./travis_bundle_dir

script: rake spec
