os:
  - osx

language: ruby
cache: bundler
rvm:
  - system
  - 1.8.7
  - 1.9.3
    # Disabled due to travis bug failing to install this ruby
    #  - 2.0.0-p247 # OS X 10.9.0 - 10.9.2
  - 2.0.0-p451 # OS X 10.9.3 - 10.9.4
  - 2.0.0-p481 # OS X 10.9.5

before_install:
  # There is a bug in travis. When using system ruby, bundler is not installed
  # and causes the default install action to fail.
  - sudo gem install bundler

addons:
 code_climate:
   repo_token: fcf708528e1eca6e8a8bf8f7be3bd24e4478b019c4cd7860325c141dd52aa152 

